"""Add recipe jobs table for async processing

Revision ID: 005
Revises: 2852b5735058
Create Date: 2025-09-11 14:50:00.000000

Note: originally chained from a '004' revision that was never committed to
this repo (production's pre-005 schema was created manually rather than via
Alembic). Re-parented onto '2852b5735058' (the initial_production_migration
baseline), which creates exactly the tables this migration's schema assumes
already exist - confirmed against production's actual pre-005 columns.

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '2852b5735058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('original_recipe_id', sa.Integer(), nullable=True),
    sa.Column('modification_prompt', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_jobs_status'), 'recipe_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_recipe_jobs_user_id'), 'recipe_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_jobs_user_id'), table_name='recipe_jobs')
    op.drop_index(op.f('ix_recipe_jobs_status'), table_name='recipe_jobs')
    op.drop_table('recipe_jobs')
    # ### end Alembic commands ###